Add a way to deep copy an object recursively
sadanandpai/javascript-code-challenges pull request #38
Opened 2021-12-05 10:24 UTC by ptbhatcoder

For [Q3](https://github.com/sadanandpai/javascript-code-challenges/blob/main/challenges/objects-challenges.md#q3) in functions challenges

2021-12-06 10:29 UTC, sadanandpai requested changes

2021-12-06 10:29 UTC, sadanandpai commented on challenges/objects-challenges.md
> +        nVal[key] = obj[key];
nVal is not declared

2021-12-06 10:29 UTC, sadanandpai commented on challenges/objects-challenges.md
> +      if(obj[key] !== 'object')
typeof is missing

2021-12-06 10:29 UTC, sadanandpai commented on challenges/objects-challenges.md
> +      copyObj[key] = val;
is there any use of val

2021-12-06 13:43 UTC, ptbhatcoder commented on challenges/objects-challenges.md
> +        nVal[key] = obj[key];
Fixed. It was `copyObj`

2021-12-06 13:43 UTC, ptbhatcoder commented on challenges/objects-challenges.md
> +      if(obj[key] !== 'object')
Fixed

2021-12-08 16:42 UTC, sadanandpai approved these changes

2021-12-08 16:43 UTC, merged

2021-12-08 16:44 UTC, sadanandpai commented
Solution does not work properly if arrays are present inside